# Generated by Django 4.1.4 on 2023-01-02 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(default=datetime.date(2023, 1, 2)),
        ),
    ]
